modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
logoFile = "assets/lobecorp/lobecorp_logo.png"
credits = "${mod_credits}"
authors = "${mod_authors}"
description = '''${mod_description}'''
displayURL = "${displayURL}"
issueTrackerURL = "${issueTrackerURL}"

[[mixins]]
config = "META-INF/lobecorp.mixins.json"

[[accessTransformers]]
file = "META-INF/accesstransformer.cfg"

[[dependencies.${ mod_id }]]
modId = "neoforge"
type = "required"
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[modproperties.${ mod_id }]
catalogueImageIcon = "assets/lobecorp/lobecorp_icon.png"
catalogueBackground = "assets/lobecorp/lobecorp_bg.png"